inherit_mode:
  merge:
    - Exclude

require:
  # - rubocop-rake
  - rubocop-performance
  - standard/cop/semantic_blocks

inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop_rails.yml
  - .rubocop_rspec.yml
  - .rubocop_strict.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - Rakefile
    - db/**/*
    - config/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - app/assets/config.rb
    - node_modules/**/*

# NB: these metrics are more strict than the values in .rubocop_strict.yml
Metrics/AbcSize:
  Max: 20
  Severity: error
Metrics/ClassLength:
  Max: 200
  Severity: error
Metrics/ModuleLength:
  Max: 200
  Severity: error
Metrics/CyclomaticComplexity:
  Max: 6
  Severity: error
Metrics/MethodLength:
  Max: 10
  Severity: error

# in specs and raks-tasks, blocks are a structure-mechanism
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - lib/tasks/*.rake

